#Login with success
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "fulano@email.com",
    "password": "123456789"
}

###
#Login without success
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json


###
#Create a list 
POST http://localhost:3000/list/create HTTP/1.1
content-Type: application/json

{
    "name": "list1",
    "color": "blue",
    "user": "8373dc6a-ccec-4fc5-bc10-ddea2265d5fa"
}

###
#Listing all lists
GET http://localhost:3000/list/all/e717a789-e158-473d-8b6f-38e3ec6a462b HTTP/1.1
content-Type: application/json


###
#Update a list 
PATCH http://localhost:3000/list HTTP/1.1
content-Type: application/json

{
    "id":   "4f434716-c482-49f8-aa36-370008f456fe",
    "name": "list3",
    "color": "purple"
}

###
#Delete a list 
DELETE  http://localhost:3000/list/5e2a186e-4bf8-40e0-85ad-580e4a83b4aa HTTP/1.1


###
#Create a task 
POST http://localhost:3000/task/create HTTP/1.1
content-Type: application/json

{
    "name": "task1",
    "listId": "016d5085-c53d-412f-8390-1e0ade31d84f"
}

###
#Listing a list 
GET http://localhost:3000/task/all/016d5085-c53d-412f-8390-1e0ade31d84f HTTP/1.1
content-Type: application/json


###
#Update a task 
PATCH http://localhost:3000/task HTTP/1.1
content-Type: application/json

{
    "id":   "a3f2d313-2712-45e8-ab27-ded44e6eb6e5",
    "name": "task3",
    "completed": true
}

###
#Delete a list 
DELETE  http://localhost:3000/task/a3f2d313-2712-45e8-ab27-ded44e6eb6e5 HTTP/1.1