#Login with success
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "fulano@email.com",
    "password": "123456789"
}

###
#Login without success
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json


###
#Create a list 
POST http://localhost:3000/list/create HTTP/1.1
content-Type: application/json

{
    "name": "list1",
    
    "user": "9450f523-5985-4fb5-b8bf-dda9ed6cea22"
}

###
#Listing all lists
GET http://localhost:3000/list/all/9450f523-5985-4fb5-b8bf-dda9ed6cea22 HTTP/1.1
content-Type: application/json


###
#Update a list 
PATCH http://localhost:3000/list HTTP/1.1
content-Type: application/json

{
    "id":   "9f2b03cb-f760-44d6-983d-7fde9100d86b",
    "name": "list3",
    "color": "purple"
}

###
#Delete a list 
DELETE  http://localhost:3000/list/a5fd32e8-2f35-4747-afe8-f2fbbf63c5f9 HTTP/1.1


###
#Create a task 
POST http://localhost:3000/task/create HTTP/1.1
content-Type: application/json

{
    "name": "task1",
    "listId": "d1d0806d-338e-4fdd-aca9-774e730a8385"
}

###
#Listing all tasks 
GET http://localhost:3000/task/all/9f2b03cb-f760-44d6-983d-7fde9100d86b HTTP/1.1
content-Type: application/json


###
#Update a task 
PATCH http://localhost:3000/task HTTP/1.1
content-Type: application/json

{
    "id":   "a3f2d313-2712-45e8-ab27-ded44e6eb6e5",
    "name": "task3",
    "completed": true
}

###
#Delete a task 
DELETE  http://localhost:3000/task/a3f2d313-2712-45e8-ab27-ded44e6eb6e5 HTTP/1.1