#Login with success
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "fulano@email.com",
    "password": "123456789"
}

###
#Login without success
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json


###
#Create a list 
POST http://localhost:3000/list/create HTTP/1.1
content-Type: application/json

{
    "name": "list1",
    "color": "blue",
    "user": "e717a789-e158-473d-8b6f-38e3ec6a462b"
}

###
#Listing all lists
GET http://localhost:3000/list/all/e717a789-e158-473d-8b6f-38e3ec6a462b HTTP/1.1
content-Type: application/json


