services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:../../../../dev.db
    volumes:
      - .:/app
      - /app/node_modules # To avoid node_modules overwrite issue
    command: npm run start:dev # Use nodemon to automatically reload
